### ISSUE TITLE
About parameters in cfg.json

### ISSUE THREAD

**Issue by RandomFool123** [zhengthomastang/MOT_Kalman#2]
Hello, I would like to ask if this method was used when you participated in 3D MOT 2015. If so, how should the parameters in cfg. json be adjusted?

**Comment by zhengthomastang** [comment]
Thank you for checking in! But sorry that this is not my complete implementation for 3D MOT 2015 - The adaptive appearance model is not included. It only shows a 2D Kalman-filter-based tracking workflow.

**Comment by RandomFool123** [comment]
> Thank you for checking in! But sorry that this is not my complete implementation for 3D MOT 2015 - The adaptive appearance model is not included. It only shows a 2D Kalman-filter-based tracking workflow.

So what should I do if I want to achieve the good results you showed in 3D MOT 2015?

**Comment by zhengthomastang** [comment]
Sorry. The code for that algorithm cannot be fully disclosed for it is under license. But we do have another open-source single-camera tracker for the AI City Challenge Workshop in CVPR 2018.  Here is the [link](https://github.com/zhengthomastang/2018AICity_TeamUW) to my repository.

**Comment by RandomFool123** [comment]
> Sorry. The code for that algorithm cannot be fully disclosed for it is under license. But we do have another open-source single-camera tracker for the AI City Challenge Workshop in CVPR 2018. Here is the [link](https://github.com/zhengthomastang/2018AICity_TeamUW) to my repository.


Ok, thank you very much.
